# Generated by Django 2.1.5 on 2020-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='front_image_thumbnail',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
