# Generated by Django 2.1.5 on 2020-05-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_front_image_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='back_image',
            new_name='back_image_large',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='front_image',
            new_name='back_image_small',
        ),
        migrations.AddField(
            model_name='product',
            name='front_image_large',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='front_image_small',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
