# Generated by Django 2.1.5 on 2020-05-21 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200521_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('shipment_type', models.CharField(choices=[('purchase', 'purchase'), ('return', 'return')], max_length=8)),
                ('status', model_utils.fields.StatusField(choices=[('created', 'created'), ('label_pending', 'label_pending'), ('label_generated', 'label_generated'), ('in-transit', 'in-transit'), ('received', 'received'), ('error', 'error')], default='created', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('easyship_shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_id', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('destination_address_line_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 1')),
                ('destination_address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2')),
                ('destination_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('destination_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='state')),
                ('destination_postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='postal_code')),
                ('destination_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='country')),
                ('destination_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('checkpoint_time', models.DateTimeField()),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_status', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Shipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
