# Generated by Django 2.1.5 on 2020-05-25 04:01

import app.models.product
import app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shipment_shipmentcheckpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='back_image_large',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.product.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='back_image_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image_large',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.product.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image_small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='avatar photo', null=True, upload_to=app.models.user.get_upload_path),
        ),
    ]
