# Generated by Django 2.1.5 on 2020-05-26 03:46

import django_currentuser.db.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200525_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_app_product_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_by',
            field=django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_app_product_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('girl', 'Girl'), ('boy', 'Boy'), ('neutral', 'Neutral')], default='neutral', max_length=9),
        ),
    ]
