# Generated by Django 2.1.5 on 2020-05-30 15:18

import django_currentuser.db.models
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200530_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_by',
            field=django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
