# Generated by Django 3.0.6 on 2020-07-29 23:37

import django_currentuser.db.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200530_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='modified_by',
            field=django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_app_listing_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_by',
            field=django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_app_product_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('purchase', 'purchase'), ('payout', 'payout'), ('refund', 'refund')], max_length=8),
        ),
    ]
