# Generated by Django 3.0.6 on 2020-08-06 22:28

import app.models.product
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_expiringtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True,
                upload_to=app.models.product.get_upload_path,
                verbose_name='back image'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_image',
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True,
                upload_to=app.models.product.get_upload_path,
                verbose_name='front image'),
        ),
    ]
