# Generated by Django 3.0.6 

from django.db import migrations
from django.db.models import F


def copy_original_image_columns_to_sorl(apps, schema_editor):
    ProductModel = apps.get_model('app', 'Product')
    ProductModel.objects.filter(
            front_image__isnull=True,
            front_image_large__isnull=False
        ).update(
            front_image=F('front_image_large'))
    ProductModel.objects.filter(
            back_image__isnull=True,
            back_image_large__isnull=False
        ).update(
            back_image=F('back_image_large'))


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sorl_img_fields_in_listing_item'),
    ]

    operations = [
        migrations.RunPython(copy_original_image_columns_to_sorl)
    ]
