# Generated by Django 3.0.6 on 2020-08-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_move_original_listing_images_to_sorl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='back_image_large',
        ),
        migrations.RemoveField(
            model_name='product',
            name='back_image_small',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_image_large',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_image_small',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_image_thumbnail',
        ),
    ]
