# Generated by Django 3.0.6 on 2020-08-07 23:29

import app.models.user
from django.db import migrations, models
import django_fsm
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_front_back_image_to_image_large'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=django_fsm.FSMField(
                choices=[
                    ('draft', 'draft'),
                    ('published', 'published'),
                    ('sold', 'sold'),
                    ('shipped', 'shipped'),
                    ('received', 'received')
                ], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether this user should be treated as active.',
                verbose_name='active'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(
                blank=True, help_text='avatar photo', null=True,
                upload_to=app.models.user.get_upload_path
            ),
        ),
    ]
