# Generated by Django 3.0.6 on 2020-08-08 00:49

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_listing_status_to_fsmfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=django_fsm.FSMField(
                choices=[
                    ('created', 'created'),
                    ('label_pending', 'label pending'),
                    ('label_generated', 'label generated'),
                    ('in-transit', 'in transit'),
                    ('error', 'error')
                ],
                default='created', max_length=50
            ),
        ),
    ]
