# Generated by Django 3.0.6 on 2020-08-08 10:53

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_shipment_status_converted_to_fsmfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'pending'), ('complete', 'complete')], default='pending', max_length=50),
        ),
    ]
