# Generated by Django 3.0.6 on 2020-08-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_transaction_model_fsm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByndeAccount',
            fields=[
            ],
            options={
                'verbose_name': 'account',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.account',),
        ),
        migrations.CreateModel(
            name='ByndeCustomer',
            fields=[
            ],
            options={
                'verbose_name': 'customer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.customer',),
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='app.ByndeAccount', verbose_name='Connected Account'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='app.ByndeCustomer', verbose_name='Connected Account'),
        ),
    ]
