# Generated by Django 3.0.6 on 2020-08-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_account_and_customer_to_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_stripe_connected',
        ),
    ]
