# Generated by Django 3.0.6 on 2020-09-04 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_user_is_stripe_connected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByndePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.Listing')),
                ('payment_intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='djstripe.PaymentIntent')),
            ],
        ),
    ]
