# Generated by Django 3.0.6 on 2020-09-07 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_create_byndepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='platform_fee_pct',
            field=models.DecimalField(
                blank=True, decimal_places=4,
                default=0.01, max_digits=5, null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(0.9)]),
        ),
    ]
