# Generated by Django 3.0.6 on 2020-09-09 06:11

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_validation_to_platform_fee_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='byndepayment',
            options={'ordering': ('-modified',), 'verbose_name': 'payment'},
        ),
        migrations.AddField(
            model_name='byndepayment',
            name='created',
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False,
                verbose_name='created'),
        ),
        migrations.AddField(
            model_name='byndepayment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False,
                verbose_name='modified'),
        ),
    ]
