# Generated by Django 3.0.6 on 2020-09-10 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_add_timestamps_to_payments_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='height',
            field=models.IntegerField(
                default=10, validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(100)
                ], verbose_name='height in cm'),
        ),
        migrations.AddField(
            model_name='listing',
            name='length',
            field=models.IntegerField(
                default=10, validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(100)
                ], verbose_name='length in cm'),
        ),
        migrations.AddField(
            model_name='listing',
            name='weight',
            field=models.FloatField(
                default=1, validators=[
                    django.core.validators.MinValueValidator(1)
                ], verbose_name='actual weight in kg'),
        ),
        migrations.AddField(
            model_name='listing',
            name='width',
            field=models.IntegerField(
                default=10, validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(100)
                ], verbose_name='width in cm'),
        ),
    ]
