# Generated by Django 3.0.6 on 2020-09-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_add_size_columns_to_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='easyship_shipment_id',
            new_name='easypost_shipment_id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_url',
            field=models.URLField(blank=True, null=True, verbose_name='label url'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
