# Generated by Django 3.0.6 on 2020-09-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_shipment_model_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='listing',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shipments', to='app.Listing'),
        ),
    ]
