# Generated by Django 3.0.6 on 2020-09-14 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_shipment_linked_to_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='purchased_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='purchased_listings',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.OneToOneField(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user', to='app.ByndeCustomer',
                verbose_name='Connected Customer'),
        ),
    ]
