# Generated by Django 3.0.6 on 2020-09-19 12:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_add_purchased_by_to_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='tracking_id',
        ),
        migrations.CreateModel(
            name='ShipmentTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easypost_id', models.CharField(max_length=48, verbose_name='easypost tracker id')),
                ('tracking_code', models.CharField(blank=True, max_length=48, null=True)),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('signed_by', models.CharField(blank=True, max_length=40, null=True, verbose_name='signed by')),
                ('est_delivery_date', models.DateTimeField(verbose_name='estimated delivery date')),
                ('tracking_details', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='tracking details')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='app.Shipment')),
            ],
            options={
                'verbose_name': 'tracker',
                'verbose_name_plural': 'trackers',
                'ordering': ('-updated_at',),
            },
        ),
    ]
