# Generated by Django 3.0.6 on 2020-09-19 19:37

import django_currentuser.db.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_add_purchased_by_to_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='shipping_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reported', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, max_length=10000)),
                ('created_by', django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_listingreport_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.Listing')),
                ('modified_by', django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_app_listingreport_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
