# Generated by Django 3.0.6 on 2020-09-21 17:30

import django_currentuser.db.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200919_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, max_length=10000)),
                ('created_by', django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_listingrating_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.Listing')),
                ('modified_by', django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_app_listingrating_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
