# Generated by Django 3.0.6 on 2020-09-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_create_shipment_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasableListing',
            fields=[
            ],
            options={
                'verbose_name': 'releasable listing',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.listing',),
        ),
    ]
