# Generated by Django 3.0.6 on 2020-09-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_create_releasablelisting_proxy_model'),
        ('app', '0030_listingrating'),
    ]

    operations = [
    ]
