# Generated by Django 3.0.6 on 2020-09-22 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_merge_20200922_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='platform_fee_pct',
            field=models.DecimalField(
                blank=True, decimal_places=4, default=1, max_digits=5,
                null=True, validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='purchased_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='purchased_listings',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
