# Generated by Django 3.0.6 on 2020-09-23 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_platform_fee_pct_column_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='platform_fee_pct',
            field=models.DecimalField(
                blank=True, decimal_places=4, default=1,
                help_text='platform fee percent from 0 to 10',
                max_digits=5, null=True, validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10)]),
        ),
    ]
