# Generated by Django 3.0.6 on 2020-09-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_add_brand_cat_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttracker',
            name='est_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery date'),
        ),
    ]
