# Generated by Django 3.0.6 on 2020-09-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_est_delivery_date_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
