# Generated by Django 3.0.6 on 2020-09-25 09:40

from django.db import migrations
from django.contrib.auth import get_user_model


def create_cart_for_existing_users(apps, schema_editor):
    User = get_user_model()
    Cart = apps.get_model('app', 'Cart')

    if not User.objects.count():
        return

    for item in User.objects.all().values('pk'):
        Cart.objects.create(user_id=item['pk'])


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_create_cart_cartitem_n_publishedlisting'),
    ]

    operations = [
        migrations.RunPython(create_cart_for_existing_users, do_nothing),
    ]
