# Generated by Django 3.0.6 on 2020-09-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200925_1735'),
        ('app', '0038_initialize_cart_for_existing_users'),
    ]

    operations = [
    ]
