# Generated by Django 3.0.6 on 2020-09-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='listing',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_item',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='shipment', to='app.OrderItem'),
        ),
        migrations.DeleteModel(
            name='ByndePayment',
        ),
    ]
