# Generated by Django 3.0.6 on 2020-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_recreate_bynde_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='express_dashboard',
            field=models.URLField(blank=True, null=True, verbose_name='stripe express dashboard link'),
        ),
    ]
