# Generated by Django 3.0.6 on 2020-10-06 13:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_express_dashboard_column_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(
                blank=True, max_length=255, null=True,
                verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(
                blank=True, max_length=255, null=True,
                verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(
                blank=True, max_length=255, null=True,
                verbose_name='country'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True,
                verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(
                blank=True, max_length=15, null=True,
                verbose_name='postal_code'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='state'),
        ),
    ]
