# Generated by Django 3.0.6 on 2020-10-16 08:55

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_add_address_info_columns_into_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='destination_address_line_1',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination_address_line_2',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination_country',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination_phone',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination_postal_code',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination_state',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=django_fsm.FSMField(
                choices=[
                    ('a', 'active'), ('c', 'canceled'), ('r', 'in return')],
                default='a', max_length=50, verbose_name='order item status'),
        ),
    ]
