# Generated by Django 3.0.6 on 2020-10-17 16:42

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_status_into_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=django_fsm.FSMField(choices=[('a', 'active'), ('s', 'ready to ship'), ('i', 'in progress of label printing'), ('p', 'postage label purchased'), ('f', 'failed to print postage label'), ('d', 'received'), ('c', 'canceled'), ('r', 'in return')], default='a', max_length=50, verbose_name='order item status'),
        ),
    ]
