# Generated by Django 3.0.6 on 2020-10-22 01:31

import app.models.product
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_fsm
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_extend_order_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg_removal_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='bg_removal_status',
            field=django_fsm.FSMField(choices=[
                ('t', 'to do'), ('p', 'pending'), ('i', 'in progress'),
                ('d', 'done'), ('f', 'failed')], default='t', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='bg_removal_task_uuid',
            field=models.UUIDField(
                blank=True, null=True, verbose_name='background removal task id'),
        ),
        migrations.AddField(
            model_name='product',
            name='bg_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bg_removed_back_image_large',
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to=app.models.product.get_upload_path,
                verbose_name='back image without background'),
        ),
        migrations.AddField(
            model_name='product',
            name='bg_removed_front_image_large',
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to=app.models.product.get_upload_path,
                verbose_name='front image without background'),
        ),
    ]
