# Generated by Django 3.0.6 on 2020-10-22 06:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_add_bg_removal_fields_to_listing_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bg_removal_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True),
        ),
    ]
