# Generated by Django 3.0.6 on 2020-10-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_nullable_bg_removed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentCheckpoint',
        ),
    ]
