# Generated by Django 3.0.6 on 2020-10-23 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_delete_shipmentcheckpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('easypost_id', models.CharField(
                    max_length=48, verbose_name='easypost pickup id')),
                ('min_datetime', models.DateTimeField(
                    verbose_name='min datetime')),
                ('max_datetime', models.DateTimeField(
                    verbose_name='max datetime')),
                ('status', django_fsm.FSMField(
                    choices=[
                        ('unknown', 'unknown'), ('scheduled', 'scheduled'),
                        ('canceled', 'canceled')],
                    default='unknown', max_length=50)),
                ('shipment', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pickup', to='app.Shipment')),
            ],
            options={
                'verbose_name': 'pickup',
                'ordering': ('-modified',),
            },
        ),
    ]
