# Generated by Django 3.0.6 on 2020-10-24 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_create_pickup_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(max_length=64, unique=True, verbose_name='rate type')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='rate')),
            ],
            options={
                'verbose_name': 'shipping rate',
                'ordering': ('rate',),
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='app.ShippingRate', verbose_name='shipping type'),
        ),
    ]
