# Generated by Django 3.0.6 on 2020-10-28 13:52

import app.fields
import app.models.product
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_create_shipping_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_image_large',
            field=app.fields.ProductImageField(
                blank=True, null=True,
                upload_to=app.models.product.get_upload_path,
                verbose_name='back image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image_large',
            field=app.fields.ProductImageField(
                blank=True, null=True,
                upload_to=app.models.product.get_upload_path,
                verbose_name='front image'),
        ),
    ]
