# Generated by Django 3.0.6 on 2020-11-14 04:11

import app.models.product
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_customized_sorl_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_image_large',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=app.models.product.get_upload_path, verbose_name='back image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image_large',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=app.models.product.get_upload_path, verbose_name='front image'),
        ),
    ]
