# Generated by Django 3.0.6 on 2020-12-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_listing_item_image_fields_rolled_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='listing',
        ),
        migrations.DeleteModel(
            name='StripeAccount',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
