# Generated by Django 3.0.6 on 2020-12-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_added_platform_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='easypost_shipment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
