# Generated by Django 3.0.6 on 2020-12-23 13:18

import django.core.validators
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_easypost_shipment_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=None, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='verification code'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=django_fsm.FSMField(choices=[('a', 'active'), ('s', 'ready to ship'), ('i', 'in progress of label printing'), ('p', 'postage label purchased'), ('f', 'failed to print postage label'), ('t', 'in transit'), ('d', 'received'), ('c', 'canceled'), ('r', 'in return')], default='a', max_length=50, verbose_name='order item status'),
        ),
    ]
