# Generated by Django 3.0.6 on 2021-01-13 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20201223_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_failed_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='verification failure counter'),
        ),
    ]
