# Generated by Django 3.0.6 on 2021-01-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_user_code_failed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='suggested',
            field=models.BooleanField(default=False, verbose_name='is suggested'),
        ),
    ]
