# Generated by Django 3.0.6 on 2021-01-14 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_slug_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='platform_fee_pct',
            field=models.DecimalField(decimal_places=3, default=15, help_text='platform fee percent from 0 to 10', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
