# Generated by Django 3.0.6 on 2021-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_cart_nullable_user_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='failure reason'),
        ),
    ]
