# Generated by Django 3.0.6 on 2021-06-24 23:12

import app.models.product
import django_currentuser.db.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20210204_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image_large', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=app.models.product.get_upload_path, verbose_name='image large')),
                ('bg_removed_image_large', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=app.models.product.get_upload_path, verbose_name='background removed image large')),
                ('bg_removal_status', django_fsm.FSMField(choices=[('t', 'to do'), ('p', 'pending'), ('i', 'in progress'), ('d', 'done'), ('f', 'failed')], default='t', max_length=50)),
                ('bg_removal_task_uuid', models.UUIDField(blank=True, null=True, verbose_name='background removal task id')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_images', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Product')),
                ('modified_by', django_currentuser.db.models.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_app_listingimage_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
