# Generated by Django 3.0.6 on 2021-06-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20210204_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('order', '-modified'), 'verbose_name': 'order item'},
        ),
    ]
