# Generated by Django 3.0.6 on 2021-06-27 21:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='bg_removal_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='bg_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
