# Generated by Django 3.0.6 on 2021-06-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_appleloginmodel_appleloginmodelbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleLoginSerialzerBase',
            fields=[
                ('appleId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppleLoginSerialzerBaseExtends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('appleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='app.AppleLoginSerialzerBase')),
            ],
        ),
        migrations.CreateModel(
            name='AppleLoginSerialzerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('appleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.AppleLoginSerialzerBaseExtends')),
            ],
        ),
        migrations.DeleteModel(
            name='AppleLoginModel',
        ),
        migrations.DeleteModel(
            name='AppleLoginModelBase',
        ),
    ]
