# Generated by Django 3.0.6 on 2021-07-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20210627_2109'),
        ('app', '0070_auto_20210609_2023'),
    ]

    operations = [
    ]
