# Generated by Django 3.0.6 on 2021-07-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_merge_20210705_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='circleci',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
