# Generated by Django 3.0.6 on 2021-07-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_product_circleci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='circleci',
        ),
    ]
