# Generated by Django 3.0.6 on 2021-12-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_suggestedproductbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='slug1',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='suggested',
            field=models.BooleanField(default=False, verbose_name='is Approved'),
        ),
    ]
