# Generated by Django 3.0.6 on 2021-12-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20211213_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='suggested1',
            field=models.BooleanField(default=False, verbose_name='is Approved'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='suggested',
            field=models.BooleanField(default=False, verbose_name='is suggested'),
        ),
    ]
