# Generated by Django 3.0.6 on 2021-12-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20211213_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='slug1',
        ),
    ]
