# Generated by Django 3.0.6 on 2021-12-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_remove_productbrand_slug1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbrand',
            old_name='suggested1',
            new_name='Approved',
        ),
    ]
