# Generated by Django 3.0.6 on 2021-12-15 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20211214_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='Approved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
