# Generated by Django 3.0.6 on 2021-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20211215_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='Approved',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Reject')], default=0),
        ),
    ]
