# Generated by Django 3.0.6 on 2021-12-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20211215_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='Suggested_by',
            field=models.IntegerField(blank=True, default=0),

        ),
    ]
