# Generated by Django 3.0.6 on 2021-12-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_productbrand_suggested_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingrating',
            options={'verbose_name': 'Listing Rate', 'verbose_name_plural': 'Listing Ratings'},
        ),
    ]
