# Generated by Django 3.0.6 on 2021-12-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20211217_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingrating',
            options={},
        ),
    ]
