# Generated by Django 3.0.6 on 2021-12-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20211217_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.CharField(default=True, max_length=255, null=True, verbose_name='batch_id'),
        ),
    ]
