# Generated by Django 3.0.6 on 2021-12-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20211218_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipmentid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shipment_id'),
        ),
    ]
