# Generated by Django 3.0.6 on 2021-12-29 12:02

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_orderitem_shipmentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=django_fsm.FSMField(choices=[('created', 'created'), ('label_pending', 'label pending'), ('label_generated', 'label generated'), ('in-transit', 'in transit'), ('received', 'received'), ('error', 'error')], default='created', max_length=50),
        ),
    ]
