# Generated by Django 3.0.6 on 2022-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_shipmenttracker_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttracker',
            name='tracking_url',
            field=models.CharField(max_length=255, null=True, verbose_name='tracking url'),
        ),
    ]
