# Generated by Django 3.0.6 on 2022-01-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_auto_20220110_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmenttracker',
            name='tracking_url',
        ),
    ]
