# Generated by Django 3.0.6 on 2022-01-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_remove_shipmenttracker_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttracker',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
