# Generated by Django 4.2.6 on 2023-12-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_alter_listing_buyer_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='environment',
            field=models.CharField(default='LOCAL', max_length=255),
        ),
    ]
