# Generated by Django 4.2.6 on 2024-01-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_user_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='environment_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
