# Generated by Django 4.2.6 on 2024-01-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_user_environment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='environment',
        ),
    ]
