# Generated by Django 4.2.6 on 2024-08-05 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='shipping_boxes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
