# Generated by Django 4.2.6 on 2024-08-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_listing_shipping_boxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='shipping_boxes',
        ),
    ]
