# Generated by Django 4.2.6 on 2024-08-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_remove_listing_shipping_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
