# Generated by Django 4.2.6 on 2024-09-19 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_bundle_bundlerating_bundlereport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='slug',
        ),
        migrations.AddField(
            model_name='bundle',
            name='type',
            field=django_fsm.FSMField(choices=[('outgoing', 'outgoing'), ('incoming', 'incoming')], default='outgoing', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='status',
            field=django_fsm.FSMField(choices=[('sold', 'sold'), ('shipped', 'shipped'), ('received', 'received')], default='sold', max_length=50),
        ),
    ]
