# Generated by Django 4.2.6 on 2024-09-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_remove_bundle_slug_bundle_type_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='app.bundle'),
        ),
    ]
