# Generated by Django 4.2.6 on 2024-09-22 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_alter_product_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
